spring:
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  datasource:
    username: root
    password: root-pass
    url: jdbc:mariadb://localhost:3308/JARVIS_DB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
  social:
    facebook:
      appId: 524257436231028
      secretAppKey: a45f53d2c7b335af811797e77d50cbfb
