spring:
#  h2:
#    console:
#      enabled: true
#      path: /my-h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  datasource:
    username: root
    password: root-pass
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
  social:
    facebook:
      appId: 524257436231028
      secretAppKey: a45f53d2c7b335af811797e77d50cbfb
